concurrent = 1
check_interval = 0

[[runners]]
  name = "angular"
  url = "https://gitlab.com/"
  token = "$(GITLAB_RUNNER_TOKEN)"
  executor = "docker"
  [runners.docker]
    image = "alpine:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
  [runners.cache]
    Insecure = false
